config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
resources :articles do
  resources :comments
  resources :ratings
end
root 'welcome#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
has_many :comments, dependent: :destroy
has_many :ratings,  dependent: :destroy
validates :title, presence: true,
                    length: { minimum: 5 }
validates :text, presence: true
def average_rating
    if self.ratings.size > 0
        self.ratings.average(:score)
    else
        'undefined'
    end
end

def lowest_rating
	self.ratings.minimum(:score)
end

def highest_rating
	self.ratings.maximum(:score)
end

def number_of_comments
	self.comments.count
end


def self.to_csv
  attributes = %w{title lowest_rating highest_rating average_rating number_of_comments}
  CSV.generate(headers: true) do |csv|
    csv << attributes
    all.each do |article|
      csv << attributes.map{ |attr| article.send(attr)}
    end
  end
end



end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/models/rating.rb
class Rating < ApplicationRecord
  belongs_to :article
validates :score, presence: true




end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController


http_basic_authenticate_with name: "dhh", password: "secret", except: [:index, :show]

def index
  @articles = Article.all
  respond_to do |format|
    format.html
    format.csv { send_data @articles.to_csv }
    format.xls  { send_data @articles.to_csv(col_sep: "\t") }
  end
end



def show
    @article = Article.find(params[:id])	
  end
def new
  @article = Article.new
end




def edit
  @article = Article.find(params[:id])
end
 
def create
  @article = Article.new(article_params)
 
  if @article.save
    redirect_to @article
  else
    render 'new'
  end
end
 
def update
  @article = Article.find(params[:id])
 
  if @article.update(article_params)
    redirect_to @article
  else
    render 'edit'
  end
end

def destroy
  @article = Article.find(params[:id])
  @article.destroy
 
  redirect_to articles_path
end

private
  def article_params
    params.require(:article).permit(:title, :text)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  http_basic_authenticate_with name: "dhh", password: "secret", only: :destroy

  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    redirect_to article_path(@article)
  end

 def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to article_path(@article)
  end
 
  private
    def comment_params
      params.require(:comment).permit(:commenter, :body)
    end
end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
  def create
    @article = Article.find(params[:article_id])
    @rating = @article.ratings.create(rating_params)
    redirect_to article_path(@article)
  end

  private
    def rating_params
      params.require(:rating).permit(:score)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<%= form_with model: @article, local: true do |form| %>
 
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>
 
  <p>
    <%= form.label :text %><br>
    <%= form.text_area :text %>
  </p>
 
  <p>
    <%= form.submit %>
  </p>
 
<% end %>

app/views/articles/edit.html.erb
<h1>Edit article</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<h1>Listing Articles</h1>
<%= link_to 'New article', new_article_path %>
<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
    <th colspan="4"></th>
  </tr>
 
  <% @articles.each do |article| %>
    <tr>
      <td><%= article.title %></td>
      <td><%= article.text %></td>
      <td><%= link_to 'Show', article_path(article) %></td>
      <td><%= link_to 'Edit', edit_article_path(article) %></td>
      <td><%= link_to 'Destroy', article_path(article),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
      <td><%= article.average_rating %></td>
    </tr>
  <% end %>
</table>




<p>
  Download:
  <%= link_to "CSV", articles_path(format: "csv") %>
</p>

app/views/articles/index.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Sheet1">
    <Table>
      <Row>
        <Cell><Data ss:Type="String">Title</Data></Cell>
      </Row>
    <% @articles.each do |article| %>
      <Row>
        <Cell><Data ss:Type="String"><%= article.title %></Data></Cell>
      </Row>
    <% end %>
    </Table>
  </Worksheet>
</Workbook>

app/views/articles/new.html.erb
<h1>New article</h1>

<%= render 'form' %>

  
  <%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>
 
<p>
  <strong>Text:</strong>
  <%= @article.text %>
</p>

<h2>Comments</h2>
<%= render @article.comments %>

<h2>Ratings</h2>
<% @article.ratings.each do |rating| %>
  <p>
    <strong>Score:</strong>
    <%= rating.score %>
  </p>
  <% end %>


<h2>Add a rating:</h2>
<%= form_with(model: [ @article, @article.ratings.build ], local: true) do |form| %>
  <p>
    <%= form.label :score %><br>
    <%= number_field(:rating, :score, in: 1..5, step: 1) %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>


<h2>Add a comment:</h2>
<%= render 'comments/form' %>

<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>

app/views/comments/_comment.html.erb
<p>
  <strong>Commenter:</strong>
  <%= comment.commenter %>
</p>
 
<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>

<p>
  <%= link_to 'Destroy Comment', [comment.article, comment],
               method: :delete,
               data: { confirm: 'Are you sure?' } %>
</p>

app/views/comments/_form.html.erb
<%= form_with(model: [ @article, @article.comments.build ], local: true) do |form| %>
  <p>
    <%= form.label :commenter %><br>
    <%= form.text_field :commenter %>
  </p>
  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Challenge</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/ratings/_rating.html.erb
<% @article.ratings.each do |rating| %>
  <p>
    <strong>Score:</strong>
    <%= rating.score %>
  </p>
 
<% end %>

app/views/welcome/index.html.erb
<h1>Hello, Rails!</h1>
<%= link_to 'My Blog', controller: 'articles' %>